services:
  - type: web
    name: group-home-scheduler
    env: python
    region: ohio
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn "app:app"
    pythonVersion: 3.11.0
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: group_home_scheduler_db
          property: connectionString
      - key: FLASK_APP
        value: app
      - key: GUNICORN_WORKERS
        value: "4"
      - key: GUNICORN_TIMEOUT
        value: "120"
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: group-home-scheduler-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: group_home_scheduler_db
    databaseName: group_home_scheduler
    plan: free
    region: ohio 