services:
  - type: web
    name: grouphomescheduler
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python -c "
      from app import create_app, db
      from app.models import Caregiver, Shift
      app = create_app()
      with app.app_context():
          db.drop_all()
          db.create_all()
      " && gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grouphomescheduler-db
          property: connectionString
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: GUNICORN_WORKERS
        value: "4"
      - key: GUNICORN_TIMEOUT
        value: "120"
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: group-home-scheduler-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: grouphomescheduler-db
    databaseName: grouphomescheduler
    user: grouphomescheduler
    plan: free
    ipAllowList: [] 